import Head from "next/head";

import UserInfo from "@/components/pages/Homepage/UserInfo";
import MainContent from "@/components/pages/Homepage/MainContent";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="bg-[#0F172A] text-primary w-full min-h-screen">
				<section className="w-full lg:gap-8 h-auto max-w-6xl md:px-4 mx-auto flex lg:flex-row flex-col items-start justify-between">
					<UserInfo />
					<MainContent />
				</section>
			</main>
		</>
	);
}
